import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'screens/admin_dashboard_screen.dart';
import 'screens/login_screens.dart';
import 'screens/user_dashboard_screen.dart';
import 'services/auth_service.dart';

void main() async {
  // Ensure Flutter binding is initialized before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Content Manager',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFFF6B2C),
          brightness: Brightness.light,
          primary: const Color(0xFFFF6B2C),
          background: const Color(0xFFFFF8F4),
          surface: Colors.white,
        ),
        scaffoldBackgroundColor: const Color(0xFFFFF8F4),
        useMaterial3: true,
        fontFamily: 'Roboto',
      ),
      // ── Auth Gate: decides which screen to show on startup ──
      home: const AuthGate(),
    );
  }
}

/// AuthGate listens to Firebase auth state and routes accordingly:
/// - Not logged in  → LoginScreen
/// - Admin UID      → AdminDashboardScreen
/// - Regular user   → UserDashboardScreen
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = AuthService();

    return StreamBuilder<User?>(
      stream: authService.authStateChanges,
      builder: (context, snapshot) {
        // While Firebase determines auth state, show a loading screen
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: Color(0xFFFFF8F4),
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(color: Color(0xFFFF6B2C)),
                  SizedBox(height: 16),
                  Text(
                    'Initializing...',
                    style: TextStyle(color: Color(0xFF9A7060), fontSize: 14),
                  ),
                ],
              ),
            ),
          );
        }

        final user = snapshot.data;

        // No user → show login
        if (user == null) {
          return const LoginScreen();
        }

        // User is logged in → check role
        if (authService.isAdmin(user.uid)) {
          return const AdminDashboardScreen();
        } else {
          return const UserDashboardScreen();
        }
      },
    );
  }
}
